apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: otacon-system

resources:
  - ../../manifests/install.yaml
  - ../../crds/otacon-crds.yaml

commonLabels:
  app.kubernetes.io/name: otacon
  app.kubernetes.io/managed-by: kustomize

images:
  - name: ghcr.io/merthan/otacon
    newTag: latest
